import assert from "node:assert/strict";
import { createHash, randomUUID } from "node:crypto";
import { chmod, lstat, mkdir, mkdtemp, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { BROWSER_DATA_COMPATIBILITY } from "../../src/platform/node/browser-data-compatibility";

import { renderLocalBrowserWorkbenchInstaller } from "./browser-installer";
import type { BrowserInstallerTarget } from "./browser-installer-evidence";
import { run, replaceConstant } from "./browser-qualification-process";
import { createBrowserVaultFixture, verifyBrowserNativeWorkers } from "./browser-vault-fixture";
import {
  BROWSER_UPGRADE_CHECKS,
  browserUpgradePredecessor,
  validateBrowserUpgradeEvidence,
  type BrowserBackupEvidence,
  type BrowserUpgradeEvidence,
} from "./browser-upgrade-evidence";

// Frozen published assets from the exact reviewed predecessor, never regenerated by current tools.
const PREDECESSOR_ASSETS = {
  "install-browser-workbench.sh":
    "f1f16ad9c8a65fb1f0fbd6db6c177993273260252e628b022f83f6a9ba2ce5de",
  "streamskope-0.10.3-container.json":
    "b0ca2f06b5840867188a8f490e47e3f0e893f73317923c81df10126bc641032f",
  "streamskope-0.10.3.clab.yml": "641229fcfbc5bca54810f80274303668284c44f75ff408075a2025149f11e1f9",
} as const;
function sha(value: string | Buffer): string {
  return createHash("sha256").update(value).digest("hex");
}
function object(value: unknown): Record<string, unknown> {
  assert.ok(value !== null && typeof value === "object" && !Array.isArray(value));
  return value as Record<string, unknown>;
}
async function json(path: string): Promise<Record<string, unknown>> {
  const stat = await lstat(path);
  assert.ok(stat.isFile() && stat.nlink === 1 && stat.size <= 1024 * 1024);
  return object(JSON.parse(await readFile(path, "utf8")));
}
function canonical(value: unknown): string {
  if (Array.isArray(value)) return `[${value.map(canonical).join(",")}]`;
  if (value !== null && typeof value === "object")
    return `{${Object.entries(value)
      .sort(([a], [b]) => a.localeCompare(b, "en"))
      .map(([key, item]) => `${JSON.stringify(key)}:${canonical(item)}`)
      .join(",")}}`;
  return JSON.stringify(value);
}
interface Entry {
  path: string;
  type: "directory" | "file";
  mode: number;
  uid: number;
  gid: number;
  bytes: number;
  sha256: string | null;
}
async function inventory(root: string): Promise<readonly Entry[]> {
  const entries: Entry[] = [];
  let bytes = 0;
  const visit = async (relative: string): Promise<void> => {
    const path = join(root, relative);
    const stat = await lstat(path);
    assert.ok(entries.length < 512 && (stat.isDirectory() || (stat.isFile() && stat.nlink === 1)));
    bytes += stat.isFile() ? stat.size : 0;
    assert.ok(bytes < 16 * 1024 * 1024);
    entries.push({
      path: relative,
      type: stat.isDirectory() ? "directory" : "file",
      mode: stat.mode & 0o7777,
      uid: stat.uid,
      gid: stat.gid,
      bytes: stat.isFile() ? stat.size : 0,
      sha256: stat.isFile() ? sha(await readFile(path)) : null,
    });
    if (stat.isDirectory())
      for (const name of (await readdir(path)).sort())
        await visit(relative ? `${relative}/${name}` : name);
  };
  await visit("");
  return entries.sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0));
}
async function docker(
  args: readonly string[],
  environment = process.env,
): Promise<Record<string, unknown>> {
  const value: unknown = JSON.parse(
    (await run("docker", ["--host", "unix:///var/run/docker.sock", ...args], environment)).stdout,
  );
  assert.ok(Array.isArray(value) && value.length === 1);
  return object(value[0]);
}
async function verifyImage(
  target: BrowserInstallerTarget,
  environment = process.env,
): Promise<void> {
  const value = await docker(["image", "inspect", target.imageId], environment);
  const labels = object(object(value.Config).Labels);
  assert.equal(value.Id, target.imageId);
  assert.equal(`${String(value.Os)}/${String(value.Architecture)}`, target.platform);
  assert.equal(labels["org.opencontainers.image.version"], target.version);
  assert.equal(labels["org.opencontainers.image.revision"], target.sourceRevision);
}
function scopedInstaller(
  source: string,
  state: string,
  lab: string,
  container: string,
  network: string,
): string {
  for (const [key, value] of Object.entries({
    INSTALL_ROOT: state,
    LAB_NAME: lab,
    CONTAINER_NAME: container,
    NETWORK_NAME: network,
  }))
    source = replaceConstant(source, key, value);
  return source;
}
async function generations(state: string): Promise<readonly string[]> {
  return readdir(join(state, "backups")).then(
    (names) => names.sort(),
    (error: unknown) => {
      if (error instanceof Error && "code" in error && error.code === "ENOENT") return [];
      throw error;
    },
  );
}
async function verifyNewBackup(
  state: string,
  before: readonly string[],
  source: BrowserInstallerTarget,
  expected: {
    operation: "upgrade" | "rollback";
    target: BrowserInstallerTarget;
    candidateId: string;
  },
): Promise<BrowserBackupEvidence> {
  const created = (await generations(state)).filter((name) => !before.includes(name));
  assert.equal(
    created.length,
    1,
    "Transition must retain exactly one new complete backup generation.",
  );
  const transactionId = created[0]!;
  assert.match(
    transactionId,
    /^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/u,
  );
  const generation = join(state, "backups", transactionId);
  const attempts = await readdir(generation);
  assert.deepEqual(attempts, ["attempt-1"]);
  const attempt = join(generation, "attempt-1");
  const bytes = await readFile(join(attempt, "inventory.json"));
  const manifest = await json(join(attempt, "inventory.json"));
  assert.equal(manifest.schemaVersion, 1);
  assert.equal(manifest.transactionId, transactionId);
  assert.equal(manifest.attempt, 1);
  const recordedSource = object(manifest.source);
  assert.equal(recordedSource.version, source.version);
  assert.equal(recordedSource.sourceRevision, source.sourceRevision);
  assert.equal(recordedSource.imageId, source.imageId);
  const entries = await inventory(join(attempt, "data"));
  assert.deepEqual(
    manifest.entries,
    entries,
    "Backup bytes, owners and modes must match the completed inventory.",
  );
  assert.equal(manifest.dataSnapshotSha256, sha(`${canonical(entries)}\n`));
  const transaction = await json(join(attempt, "transaction.json"));
  assert.equal(transaction.phase, "committed");
  assert.equal(transaction.transactionId, transactionId);
  assert.equal(transaction.operation, expected.operation);
  assert.equal(transaction.candidateId, expected.candidateId);
  assert.equal(object(transaction.from).imageId, source.imageId);
  assert.equal(object(transaction.to).imageId, expected.target.imageId);
  assert.equal(object(transaction.to).sourceRevision, expected.target.sourceRevision);
  assert.deepEqual(transaction.nextRecord, await json(join(state, "installation.json")));
  const completed = object(transaction.backup);
  assert.equal(completed.inventorySha256, sha(bytes));
  assert.equal(completed.dataSnapshotSha256, manifest.dataSnapshotSha256);
  for (const path of [join(state, "backups"), generation, attempt]) {
    const stat = await lstat(path);
    assert.ok(stat.isDirectory() && (stat.mode & 0o077) === 0);
  }
  return { inventorySha256: sha(bytes), dataSnapshotSha256: String(manifest.dataSnapshotSha256) };
}

/** Both public delivery and local rehearsal execute this same real transaction cycle. */
export async function verifyBrowserUpgrade(options: {
  readonly target: BrowserInstallerTarget;
  readonly installerSource: string;
  readonly environment?: NodeJS.ProcessEnv;
}): Promise<BrowserUpgradeEvidence> {
  assert.equal(process.platform, "linux");
  assert.equal(process.getuid?.(), 0);
  const uid = Number(process.env.SUDO_UID);
  const gid = Number(process.env.SUDO_GID);
  assert.ok(Number.isSafeInteger(uid) && uid > 0 && Number.isSafeInteger(gid) && gid >= 0);
  const { target } = options;
  const predecessor = browserUpgradePredecessor(target.platform);
  assert.notEqual(target.imageId, predecessor.imageId);
  const temporary = await mkdtemp(join(tmpdir(), "streamskope-upgrade-qualification-"));
  await chmod(temporary, 0o700);
  const state = join(temporary, "deployment");
  const lab = `streamskope-upgrade-${randomUUID().slice(0, 12)}`;
  const container = `clab-${lab}-app`;
  const network = `${lab}-mgmt`;
  const data = join(state, "streamskope-data");
  const installer = join(temporary, "target.sh");
  const baselineInstaller = join(temporary, "predecessor.sh");
  const environment = {
    ...options.environment,
    ...process.env,
    ...(options.environment ?? {}),
    DOCKER_HOST: "unix:///var/run/docker.sock",
    DOCKER_CONTEXT: "default",
    DOCKER_CONFIG: join(temporary, "docker-config"),
  };
  const savedEnvironment = ["DOCKER_HOST", "DOCKER_CONTEXT", "DOCKER_CONFIG"].map(
    (key) => [key, process.env[key]] as const,
  );
  for (const key of ["DOCKER_HOST", "DOCKER_CONTEXT", "DOCKER_CONFIG"] as const)
    process.env[key] = environment[key];
  await mkdir(environment.DOCKER_CONFIG, { mode: 0o700 });
  let completed = false;
  let stage:
    | "target-identity"
    | "baseline-install"
    | "baseline-fixture"
    | "check"
    | "upgrade"
    | "upgrade-backup"
    | "target-unlock"
    | "rollback"
    | "rollback-backup"
    | "predecessor-unlock"
    | "pinned-resume"
    | "cleanup" = "target-identity";
  try {
    await verifyImage(target, environment);
    const absent = await run("docker", ["inspect", container], environment, true);
    assert.ok(absent.code !== 0 && /No such object/u.test(absent.stderr));
    const absentNetwork = await run("docker", ["network", "inspect", network], environment, true);
    assert.ok(absentNetwork.code !== 0 && /No such network|not found/u.test(absentNetwork.stderr));
    await run(
      "curl",
      [
        "--fail",
        "--silent",
        "--show-error",
        "--location",
        "--max-time",
        "60",
        "--max-filesize",
        "1048576",
        "--output",
        baselineInstaller,
        "https://github.com/asadarafat/streamskope/releases/download/v0.10.3/install-browser-workbench.sh",
      ],
      environment,
    );
    const baselineSource = await readFile(baselineInstaller, "utf8");
    assert.equal(sha(baselineSource), PREDECESSOR_ASSETS["install-browser-workbench.sh"]);
    await writeFile(
      baselineInstaller,
      scopedInstaller(baselineSource, state, lab, container, network),
      { mode: 0o700 },
    );
    await writeFile(
      installer,
      scopedInstaller(options.installerSource, state, lab, container, network),
      { mode: 0o700 },
    );
    stage = "baseline-install";
    const installed = await run("bash", [baselineInstaller], environment);
    const setupCode = (await readFile(join(data, "setup-code"), "utf8")).trim();
    assert.ok(!installed.stdout.includes(setupCode) && !installed.stderr.includes(setupCode));
    await run("docker", ["pull", predecessor.image], environment);
    await verifyImage(predecessor, environment);
    for (const name of [
      "streamskope-0.10.3-container.json",
      "streamskope-0.10.3.clab.yml",
    ] as const)
      assert.equal(sha(await readFile(join(state, name))), PREDECESSOR_ASSETS[name]);
    const original = await json(join(state, "installation.json"));
    assert.equal(original.version, predecessor.version);
    assert.equal(original.sourceRevision, predecessor.sourceRevision);
    assert.equal(original.uid, uid);
    assert.equal(original.gid, gid);
    stage = "baseline-fixture";
    const fixture = await createBrowserVaultFixture({ data, port: Number(original.port) });
    const treeBefore = await inventory(data);
    const recordBefore = await readFile(join(state, "installation.json"));
    const runningBefore = await docker(["inspect", container], environment);
    stage = "check";
    const checked = await run("bash", [installer, "check"], environment);
    fixture.assertNoSecrets(checked.stdout + checked.stderr);
    assert.deepEqual(await inventory(data), treeBefore);
    assert.deepEqual(await readFile(join(state, "installation.json")), recordBefore);
    assert.equal((await docker(["inspect", container], environment)).Id, runningBefore.Id);
    await fixture.verifyUnlocked();
    const beforeUpgrade = await generations(state);
    stage = "upgrade";
    const upgraded = await run("bash", [installer, "upgrade"], environment);
    fixture.assertNoSecrets(upgraded.stdout + upgraded.stderr);
    const targetContainer = await docker(["inspect", container], environment);
    assert.equal(targetContainer.Image, target.imageId);
    assert.notEqual(targetContainer.Id, runningBefore.Id);
    const current = await json(join(state, "installation.json"));
    assert.equal(current.schemaVersion, 2);
    assert.equal(object(current.current).version, target.version);
    assert.equal(object(current.current).sourceRevision, target.sourceRevision);
    assert.equal(object(current.previous).version, predecessor.version);
    stage = "upgrade-backup";
    const upgradeBackup = await verifyNewBackup(state, beforeUpgrade, predecessor, {
      operation: "upgrade",
      target,
      candidateId: String(targetContainer.Id),
    });
    stage = "target-unlock";
    await fixture.unlockAfterReplacement();
    verifyBrowserNativeWorkers(String(targetContainer.Id));
    const beforeRollback = await generations(state);
    stage = "rollback";
    const rolledBack = await run("bash", [installer, "rollback"], environment);
    fixture.assertNoSecrets(rolledBack.stdout + rolledBack.stderr);
    const restored = await docker(["inspect", container], environment);
    assert.equal(restored.Image, predecessor.imageId);
    assert.notEqual(restored.Id, targetContainer.Id);
    stage = "rollback-backup";
    const rolledRecord = await json(join(state, "installation.json"));
    assert.equal(object(rolledRecord.current).version, predecessor.version);
    assert.equal(object(rolledRecord.current).sourceRevision, predecessor.sourceRevision);
    assert.equal(object(rolledRecord.previous).version, target.version);
    for (const key of ["uid", "gid", "home", "operatorUid", "port"]) {
      assert.equal(current[key], original[key]);
      assert.equal(rolledRecord[key], original[key]);
    }
    const rollbackBackup = await verifyNewBackup(state, beforeRollback, target, {
      operation: "rollback",
      target: predecessor,
      candidateId: String(restored.Id),
    });
    stage = "predecessor-unlock";
    await fixture.unlockAfterReplacement();
    verifyBrowserNativeWorkers(String(restored.Id));
    await fixture.lock();
    const pinnedRecord = await readFile(join(state, "installation.json"));
    stage = "pinned-resume";
    const resumed = await run("bash", [installer], environment);
    fixture.assertNoSecrets(resumed.stdout + resumed.stderr);
    assert.deepEqual(await readFile(join(state, "installation.json")), pinnedRecord);
    assert.equal((await docker(["inspect", container], environment)).Image, predecessor.imageId);
    await fixture.unlockAfterReplacement();
    stage = "cleanup";
    const owner = await docker(["inspect", container], environment);
    assert.equal(object(object(owner.Config).Labels).containerlab, lab);
    assert.equal(
      object(object(owner.Config).Labels)["clab-topo-file"],
      join(state, `streamskope-${predecessor.version}.clab.yml`),
    );
    await run("docker", ["stop", "--time", "120", String(owner.Id)], environment);
    const stopped = await docker(["inspect", String(owner.Id)], environment);
    assert.equal(stopped.Image, predecessor.imageId);
    assert.equal(object(stopped.State).Running, false);
    assert.equal(object(stopped.State).OOMKilled, false);
    assert.equal(object(stopped.State).ExitCode, 0);
    const clab = (
      await run("sh", ["-c", "command -v containerlab || command -v clab"], environment)
    ).stdout.trim();
    await run(
      clab,
      [
        "--runtime",
        "docker",
        "destroy",
        "--topo",
        join(state, `streamskope-${predecessor.version}.clab.yml`),
        "--name",
        lab,
        "--cleanup",
        "--graceful",
        "--keep-mgmt-net",
        "--max-workers",
        "1",
      ],
      environment,
    );
    await run("docker", ["network", "rm", network], environment);
    completed = true;
    return validateBrowserUpgradeEvidence(
      {
        predecessor,
        targetImageId: target.imageId,
        upgradeBackup,
        rollbackBackup,
        checks: BROWSER_UPGRADE_CHECKS,
      },
      target,
    );
  } catch {
    throw new Error(
      `Native browser transition qualification failed at ${stage}; owned evidence retained at ${temporary}.`,
    );
  } finally {
    if (completed) await rm(temporary, { recursive: true, force: true });
    for (const [key, value] of savedEnvironment) {
      if (value === undefined) delete process.env[key];
      else process.env[key] = value;
    }
  }
}

/** Closed maintainer entry: real local image, real public predecessor, never public evidence. */
export async function verifyLocalBrowserUpgrade(
  image: string,
  version: string,
  sourceRevision: string,
): Promise<void> {
  const startedAt = new Date().toISOString();
  const inspected = await docker(["image", "inspect", image]);
  const platform = `${String(inspected.Os)}/${String(inspected.Architecture)}`;
  assert.ok(platform === "linux/amd64" || platform === "linux/arm64");
  const target = {
    image: String(inspected.Id),
    imageId: String(inspected.Id),
    version,
    sourceRevision,
    platform,
  };
  await verifyImage(target);
  const root = await mkdtemp(join(tmpdir(), "streamskope-local-delivery-"));
  await chmod(root, 0o700);
  const topologyName = `streamskope-${version}.clab.yml`;
  const topology = (await readFile("streamskope.clab.yml", "utf8")).replace(
    "${STREAMSKOPE_IMAGE:=streamskope:0.0.0-dev}",
    `\${STREAMSKOPE_IMAGE:=${target.imageId}}`,
  );
  assert.ok(topology.includes(`image: \${STREAMSKOPE_IMAGE:=${target.imageId}}`));
  const topologyPath = join(root, topologyName);
  await writeFile(topologyPath, topology, { mode: 0o600 });
  const manifest = `${JSON.stringify({ schemaVersion: 1, deliveryScope: "local-staged", version, sourceRevision, platform, imageId: target.imageId, dataCompatibility: BROWSER_DATA_COMPATIBILITY, topology: { file: topologyName, sha256: sha(topology) } }, null, 2)}\n`;
  const manifestPath = join(root, `streamskope-${version}-container.json`);
  await writeFile(manifestPath, manifest, { mode: 0o600 });
  const installerSource = renderLocalBrowserWorkbenchInstaller(
    {
      version,
      sourceRevision,
      platform,
      imageId: target.imageId,
      manifest: { path: manifestPath, sha256: sha(manifest) },
      topology: { path: topologyPath, sha256: sha(topology) },
    },
    await readFile("tools/package/install-browser-workbench.sh", "utf8"),
    await readFile("tools/package/browser-maintenance.py", "utf8"),
  );
  const output = resolve(
    `.artifacts/quality-priorities/browser-upgrade/local-${platform.split("/")[1]}.json`,
  );
  await rm(output, { force: true });
  const transition = await verifyBrowserUpgrade({ target, installerSource });
  await mkdir(resolve(".artifacts/quality-priorities/browser-upgrade"), { recursive: true });
  await writeFile(
    output,
    `${JSON.stringify({ schemaVersion: 1, deliveryScope: "local-staged", outcome: "passed", version, sourceRevision, platform, imageId: target.imageId, startedAt, completedAt: new Date().toISOString(), transition }, null, 2)}\n`,
    { mode: 0o600 },
  );
  await rm(root, { recursive: true, force: true });
  process.stdout.write(`Local native browser upgrade and rollback qualified: ${output}\n`);
}
if (process.argv[1] !== undefined && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const [image, version, source, ...extra] = process.argv.slice(2);
  if (!image || !version || !source || extra.length)
    throw new Error(
      "Usage: browser-upgrade-smoke.ts <actual-local-image> <version> <source-commit>",
    );
  void verifyLocalBrowserUpgrade(image, version, source).catch((error: unknown) => {
    process.stderr.write(
      `${error instanceof Error ? error.message : "Native browser transition qualification failed."}\n`,
    );
    process.exitCode = 1;
  });
}
