import { createHash } from "node:crypto";

import Ajv from "ajv";
import standaloneCode from "ajv/dist/standalone";

import type { CodecSchemaBundle } from "../application/record-codec-types";
import type { SchemaInspectionInput } from "../contracts/schema-inspection";
import { parseSchemaClient, type SchemaClient } from "../contracts/schema-client";

import { boundedJson } from "./record-codec-parser";

export interface SchemaClientWorkerInput {
  readonly kind: "client";
  readonly input: SchemaInspectionInput;
  readonly bundle: CodecSchemaBundle;
}
export function generateSchemaClient({ input, bundle }: SchemaClientWorkerInput): SchemaClient {
  if (
    bundle.root.schemaType !== "JSON" ||
    bundle.dependencies.length ||
    bundle.root.schema.length > 65536
  )
    throw new Error(
      "Client generation supports bounded, self-contained JSON Schema draft-07 only.",
    );
  const schema: unknown = JSON.parse(bundle.root.schema);
  boundedJson(schema);
  const allowed = new Set([
    "$schema",
    "$id",
    "title",
    "description",
    "type",
    "properties",
    "required",
    "additionalProperties",
    "items",
    "minItems",
    "maxItems",
    "minLength",
    "maxLength",
    "minimum",
    "maximum",
    "exclusiveMinimum",
    "exclusiveMaximum",
    "enum",
    "const",
  ]);
  const check = (s: unknown, depth: number): void => {
    if (depth > 16) throw new Error("Schema depth limit.");
    if (typeof s === "boolean") return;
    if (!s || typeof s !== "object" || Array.isArray(s)) throw new Error("Expected schema object.");
    const r = s as Record<string, unknown>;
    for (const key of Object.keys(r))
      if (!allowed.has(key))
        throw new Error(
          "Unsupported schema keyword. References, regexes and custom keywords are excluded.",
        );
    if (r.$schema !== undefined && r.$schema !== "http://json-schema.org/draft-07/schema#")
      throw new Error("Only draft-07 is supported.");
    if (r.properties && typeof r.properties === "object")
      for (const child of Object.values(r.properties)) check(child, depth + 1);
    if (r.items !== undefined) check(r.items, depth + 1);
    if (r.additionalProperties !== undefined) check(r.additionalProperties, depth + 1);
  };
  check(schema, 0);
  if (!Number.isInteger(bundle.root.id) || bundle.root.id < 0 || bundle.root.id > 0xffffffff)
    throw new Error("Invalid Registry id.");
  const ajv = new Ajv({
    strict: true,
    allErrors: false,
    logger: false,
    code: { source: true, optimize: false },
  });
  const validate = ajv.compile(schema as object);
  const generated = standaloneCode(ajv, validate);
  const sha256 = createHash("sha256").update(bundle.root.schema).digest("hex");
  const provenance = JSON.stringify({
    subject: input.subject,
    version: input.version,
    schemaId: bundle.root.id,
    sha256,
  });
  const source = `// StreamSkope JSON client. Wrapper: Apache-2.0; validator generated by Ajv 8.20.0 (MIT).\n// Runtime: Node.js 24; npm install --save-exact ajv@8.20.0\n${generated}\nconst validateRecord = module.exports;\nconst provenance = ${provenance};\nfunction encode(value) {\n const text = JSON.stringify(value);\n if (typeof text !== 'string' || Buffer.byteLength(text) > 65536) throw new Error('Record exceeds 64 KiB');\n if (!validateRecord(value)) throw new Error('Record does not match the pinned schema');\n const prefix = Buffer.alloc(5); prefix.writeUInt32BE(provenance.schemaId, 1);\n return Buffer.concat([prefix, Buffer.from(text, 'utf8')]);\n}\nfunction decode(bytes) {\n if (!Buffer.isBuffer(bytes) || bytes.length < 5 || bytes.length > 65541 || bytes[0] !== 0 || bytes.readUInt32BE(1) !== provenance.schemaId) throw new Error('Unexpected Registry record');\n const value = JSON.parse(new TextDecoder('utf-8', {fatal:true}).decode(bytes.subarray(5)));\n if (!validateRecord(value)) throw new Error('Record does not match the pinned schema');\n return value;\n}\nasync function send(producer, topic, value, key = null) {\n return producer.send({acks:-1, autocreateTopics:false, repeatOnStaleMetadata:false, messages:[{topic, key, value:encode(value)}]});\n}\nmodule.exports = {encode, decode, send, provenance};\n`;
  return parseSchemaClient({
    generator: "Ajv 8.20.0 standalone (MIT)",
    language: "JavaScript CommonJS",
    subject: input.subject,
    version: input.version,
    schemaId: bundle.root.id,
    sha256,
    source,
  });
}
